spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpasho
    username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true

ogging.level:
  org.hibernate.SQL: debug